repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: ^(nnreslib|tests)/.*\.py$
        args:
          - --config=setup.cfg
  - repo: https://github.com/PyCQA/pylint
    rev: v2.9.3
    hooks:
      - id: pylint
        files: ^(nnreslib|tests)/.*\.py$
        additional_dependencies:
          - pyenchant==3.2.1
          - numpy==1.18.5
          - tensorflow==2.3.1
          - pandas==1.1.4
          - prettytable==1.0.1
          - pytest==6.2.1
        args:
          - --rcfile=setup.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        files: ^(nnreslib)/.*\.py$
        additional_dependencies:
          - numpy==1.18.5
          - tensorflow==2.3.1
          - pandas==1.1.4
          - prettytable==1.0.1
          - data-science-types==0.2.23
        args:
          - --config-file=setup.cfg
  - repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
      - id: isort
        files: ^(nnreslib|tests)/.*\.py$
        args:
          - --check-only
          - --settings-path=setup.cfg
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        files: ^(nnreslib|tests)/.*\.py$
        args:
          - --fast
          - --diff
          - --check
          - --config=pyproject.toml
