name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:

env:
  MODULE_NAME: nnreslib

jobs:
  prepare-venv:
    name: prepare-venv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2.1.3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/linting.txt', 'requirements/build.txt', 'requirements/tests.txt', 'requirements/main.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Create venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install -r requirements/tests.txt -r requirements/main.txt

  linting:
    needs:
      - prepare-venv
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2.1.3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/linting.txt', 'requirements/build.txt', 'requirements/tests.txt', 'requirements/main.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Lint with flake8, pylint, pycodestyle, mypy, isort, black
        run: |
          source ./.venv/bin/activate
          python -m pytest --flake8 --pylint --pycodestyle --mypy --isort --black --keep-duplicates --junit-xml=test-results/linting_status.xml $MODULE_NAME
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

  tests:
    needs:
      - prepare-venv
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2.1.3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/linting.txt', 'requirements/build.txt', 'requirements/tests.txt', 'requirements/main.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run tests
        run: |
          source ./.venv/bin/activate
          coverage run -m pytest -v --junit-xml=test-results/pytest_status.xml tests
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
      - name: Create code coverage report
        if: always()
        run: |
          source ./.venv/bin/activate
          coverage xml || exit 0
      - name: Upload coverage result to codecov.io
        if: always()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true

  build:
    needs:
      - prepare-venv
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2.1.3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/linting.txt', 'requirements/build.txt', 'requirements/tests.txt', 'requirements/main.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Build package
        run: |
          source ./.venv/bin/activate
          python setup.py sdist bdist_wheel

  publish-test-results:
    name: Publish Tests Results
    needs:
      - linting
      - tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (success() || failure())
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: test-results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: test-results/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: true
